config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'picks#index'

  resources :picks do
    get 'next_round', on: :collection
    get 'favorite_list', on: :collection
    get 'add_favorite', on: :collection
  end

end

app/models/favoriteship.rb
class Favoriteship < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorite, class_name: "User"
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  has_many :favoriteships
  has_many :favorites, through: :favoriteships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end 
end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController
  include ActionView::Helpers::SanitizeHelper

  def initialize_session
    puts "Session Initialized\n"
  end
  
  def system_msg(ev, msg)
    broadcast_message ev, { 
      user_name: 'system', 
      received: Time.now.to_s(:short), 
      msg_body: msg
    }
  end
  
  def user_msg(ev, msg)
    # broadcast_message ev, { 
    #   user_name:  connection_store[:user][:user_name], 
    #   received:   Time.now.to_s(:short), 
    #   msg_body:   ERB::Util.html_escape(msg) 
    #   }
    sender_id = msg[:sender_id]
    msg_body = msg[:msg_body]
    sender_name = User.find(sender_id.to_i).username
    receiver_id = msg[:receiver_id].to_i
    WebsocketRails.users[receiver_id].send_message('new_message', { 
      user_name: sender_name,
      sender_id: "#{sender_id}", 
      msg_body: "#{msg_body}",
      received:   Time.now.to_s(:short)
     })
  end
  
  def client_connected
    system_msg :new_message, "client #{client_id} connected"
  end
  
  def new_message
    user_msg :new_message, message
  end
  
  def new_user
    connection_store[:user] = { user_name: sanitize(message[:user_name]) }
    broadcast_user_list
  end
  
  def change_username
    connection_store[:user][:user_name] = sanitize(message[:user_name])
    broadcast_user_list
  end
  
  def delete_user
    connection_store[:user] = nil
    system_msg "client #{client_id} disconnected"
    broadcast_user_list
  end
  
  def broadcast_user_list
    users = connection_store.collect_all(:user)
    broadcast_message :user_list, users
  end


  
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.limit(6)
  end


  def next_round
    
    array = []
    
    6.times.each { array << rand(User.count) + 1 }
    array = array.uniq

    @users = User.where(id: array)

    respond_to do |format|
      format.js
    end
  end

  def favorite_list
    @favorites = current_user.favorites.limit(6)

    respond_to do |format|
      format.js
    end
  end

  def add_favorite

    @favoriteship = current_user.favoriteships.build(favorite_id: params[:user_id].to_i)
    binding.pry
    if @favoriteship.save
      respond_to do |format|
        format.json { render :json => {status: :added} }
      end
    else
      respond_to do |format|
        format.json { render :json => {status: :add_failed} }
      end
    end
  end
end

app/controllers/prototype_controller.rb
class PrototypeController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.limit(6)
  end


  def next_round
    @users = User.limit(6)
    
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/common/_footer.html.erb
<!-- footer -->
<footer>

</footer>

app/views/common/_ga.html.erb
<!-- Google Analystic -->
  <script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
  </script>

app/views/common/_header.html.erb
<!-- header -->
<header>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TITLE</title>
    <meta name="description" content="DESCRIPTION">
    <meta name="viewport" content="width=device-width">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'modernizr' %>

  </head>
  <body class='<%= "#{controller.controller_name}-#{controller.action_name}" %>'>
      <!--[if lt IE 7]>
          <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
      <![endif]-->

  <%= render :partial => 'common/header' %>

  <%= yield %>

  <%= render :partial => 'common/footer' %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => false %>
  <%= yield :handwrite_js %>

  </body>
</html>

app/views/partials/_baozi_unit.html.erb
<li>
  <div class="baozi-unit <%= "actived" if actived == true %>">
    <img src="<%= avatar %>" alt="">
    <span class="notification-badge"><%= rand(1..99) %></span>
    <span class='user_id' style="display:none"><%= user_id %></span>
    <span class="name"><%= name %></span>
    <span class="health-point"><i class="fa fa-heart true"></i><i class="fa fa-heart true"></i><i class="fa fa-heart-o false"></i></span>
  </div>
</li>

app/views/partials/_message_layout.html.erb
<div class="message-wrapper <%= role %>">
  <div class="user-info row">
    <div class="info">
      <span class="avatar">
        <img src="<%= avatar %>" alt="">
      </span>
      <span class="name">
        <%= name %>
      </span>
    </div>
  </div>
  <div class="message-content">
    <% rand(1..3).times.each do |m| %>
      <p><%= Faker::Lorem.sentence %></p>
    <% end %>
  </div>
</div>

app/views/picks/_favorite_list.html.erb
<ul>
  <% @favorites.each do |user| %>
    <%= render partial: 'partials/baozi_unit', locals: {name: user.username, user_id: user.id, avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/rem/128.jpg", actived: false} %>
  <% end %>
</ul>

app/views/picks/_next_round.html.erb
<ul>
  <% @users.each do |user| %>
    <%= render partial: 'partials/baozi_unit', locals: {name: user.username, user_id: user.id, avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/rem/128.jpg", actived: false} %>
  <% end %>
</ul>

app/views/picks/favorite_list.js.erb
$('.baozi-list').html('<%= escape_javascript render "favorite_list" %>');

app/views/picks/index.html.erb
<div class="container">
  <div class="female-main-ui-wrapper">

    <!-- LOGO Container at top -->
    <div class="logo-bar">
      <span>LOGO</span>
    </div>

    <!-- Tab buttons -->
    <div class="tab-btn-wrapper row">
      <a href="#" class="tab-btn now">
        <span>Now</span>
      </a>
      <span><%= link_to "Favorite", favorite_list_picks_path, :remote => true, class: "tab-btn favorite" %></span>
    </div>

    <!-- Main content -->
    <div class="main-content-wrapper trans-05s">

      <!-- Baozi list -->
      <div class="baozi-list-wrapper row">
        <div class="baozi-list">
          <ul>
            <% @users.each do |user| %>
              <%= render partial: 'partials/baozi_unit', locals: {name: user.username, user_id: user.id, avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/rem/128.jpg", actived: false} %>
            <% end %>
          </ul>
        </div>
        <span><%= link_to "nest round", next_round_picks_path, :remote => true, class: "next-round-btn" %></span>
      </div>

      <!-- infomation and option area -->
      <div class="info-and-options-wrapper">
        <div class="option-list row">
          <ul>
            <li><a class="option-btn bye" href="#">Bye</a></li>
            <li><a class="option-btn add" href="#">Add</a></li>
          </ul>
        </div>
        <div class="chat-content-wrapper">
          
        </div>
        <div class="chat-form-wrapper">
          <input type="hidden" class="input-medium" id="user_name" >
          <input type="hidden" class="input-medium" id="sender" value="<%=current_user.id %>">
          <input type="hidden" class="input-medium" id="receiver">
          <input type="text" id="message" placeholder="What's in your mind...?"></input>
        </div>
      </div>

      <!-- send message button -->
      <div class="row">
        <button id="send" class="send-message">send message</button>
      </div>
    </div>
  </div>
</div>

<div id="chat" class="well" data-uri="<%= request.host %>:<%= request.port %>/websocket">
</div>

<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(Baozi.tabSelectorInit());
    $(document).ready(Baozi.baoziSelectorInit());
    $(document).ready(Baozi.sendMessageBtnInit());
  </script>
 
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

  <script type="text/javascript">
    $('.baozi-unit').click(function(){
      $('.actived').removeClass('actived');
      $(this).addClass('actived');
      $('#receiver').val($('.actived > .user_id').html());
    });

    $('.add').click(function (){
      $.ajax({
        url: '/picks/add_favorite',
        type: 'GET',
        dataType: "json",
        data: { user_id: $('#receiver').val() },
        error: function(xhr) {
          alert('Ajax request 發生錯誤');
        },
        success: function(response) {
          alert('成功加入favorite');
        }
      });
    });

   </script>
<% end %>



<!-- 
<script>
  var ws = new WebSocket("ws://localhost:8080");

ws.onmessage = function(e){
  print(e.data);
};

ws.onopen = function(e){
  log("websocket open");
  console.log(e);
};

ws.onclose = function(e){
  log("websocket close");
  console.log(e);
};

$(function(){
  $("#btn_post").click(post);
  $("#message").keydown(function(e){
    if(e.keyCode == 13) post();
  });
});

var post = function(){
  var name = $("#name").val();
  var mes = $("#message").val();
  ws.send(name+" : "+mes);
  $("input#message").val("");
};

var log = function(msg){
  console.log(msg);
  $("#chat").prepend($("<li>").text("[log] "+msg));
};

var print = function(msg){
  $("#chat").prepend($("<li>").text(msg));
};
</script>
 -->

app/views/picks/next_round.js.erb
$('.baozi-list').html('<%= escape_javascript render "next_round" %>');

app/views/prototype/index.html.erb
<div class="container">
  <div class="female-main-ui-wrapper">

    <!-- LOGO Container at top -->
    <div class="logo-bar">
      <span>LOGO</span>
    </div>

    <!-- Tab buttons -->
    <div class="tab-btn-wrapper row">
      <a href="#" class="tab-btn now">
        <span>Now</span>
      </a>
      <a href="#" class="tab-btn favorite">
        <span>Favorite</span>
      </a>
    </div>

    <!-- Main content -->
    <div class="main-content-wrapper trans-05s">

      <!-- Baozi list -->
      <div class="baozi-list-wrapper row">
        <div class="baozi-list">
          <ul>
            <% @users.each do |user| %>
              <%= render partial: 'partials/baozi_unit', locals: {name: user.id, user_id: user.id, avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/rem/128.jpg", actived: false} %>
            <% end %>
          </ul>
        </div>
        <a href="#" class="next-round-btn">
          <span>Next Round</span>
        </a>
      </div>

      <!-- infomation and option area -->
      <div class="info-and-options-wrapper">
        <div class="option-list row">
          <ul>
            <li><a class="option-btn bye" href="#">Bye</a></li>
            <li><a class="option-btn add" href="#">Add</a></li>
          </ul>
        </div>
        <div class="chat-content-wrapper">
          <%= render partial: 'partials/message_layout', locals: {role: 'baozi', avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/rem/128.jpg', name: 'Deja Hauck'} %>
          <%= render partial: 'partials/message_layout', locals: {role: 'self', avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/pixeliris/128.jpg', name: 'pixeliris'} %>
        </div>
        <div class="chat-form-wrapper">
          <input type="text" class="input-medium" id="sender" value="<%= current_user.id %>">
          <input type="text" class="input-medium" id="receiver">
          <form action="#test">
            <textarea type="text" id="message" placeholder="What's in your mind...?"></textarea>
            <button type="submit" hidden onclick="client_send();">Submit</button>
          </form>
        </div>
      </div>

      <!-- send message button -->
      <div class="row">
        <button id="send" class="send-message">send message</button>
      </div>
    </div>
  </div>
</div>


<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(Baozi.tabSelectorInit());
    $(document).ready(Baozi.baoziSelectorInit());
    $(document).ready(Baozi.sendMessageBtnInit());
  </script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

  <script type="text/javascript">
    $('.baozi-unit').click(function(){
      $('.actived').removeClass('actived');
      $(this).addClass('actived');
      $('#receiver').val($('.actived > .user_id').html());
    });


    dispatcher = new WebSocketRails('localhost:3000/websocket');

    dispatcher.on_open = function(data) {
      console.log('Connection has been established: ', data);
      createGuestUser();
      // dispatcher.subscribe('pumpbox');    
      bindEvents();
    };

    dispatcher.on_close = function(data) {
      console.log('Connection has been closed: ', data);
      
    };
    

    function bindEvents(){
      console.log('Connection bind');
      dispatcher.bind('new_message', newMessage);
      $('#send').on('click', sendMessage);
    }


    function appendMessage(message) {
      $('.chat-content-wrapper').append(message["msg_body"] + "</br>");
    }

    function newMessage(message) {
      console.log('receive a new message');
      appendMessage(message);
    }

    function sendMessage(event){
      console.log('send message');
      event.preventDefault();
      message = $('#message').val();
      sender_id = $('#sender').val();
      receiver_id = $('#receiver').val();
      dispatcher.trigger('new_message', {sender_id: sender_id, msg_body: message, send_to: receiver_id});
      $('.chat-content-wrapper').append("you say : " + message + "</br>");
      $('#message').val('')  
    }

    function createGuestUser(){
      user = $('#sender').val();
      dispatcher.trigger('new_user', user);
    }

    // //start on socekt
    // var currentChannel = undefined
    // var dispatcher = null;

    
    
    

    

  </script>
<% end %>



<!-- 
<script>
  var ws = new WebSocket("ws://localhost:8080");

ws.onmessage = function(e){
  print(e.data);
};

ws.onopen = function(e){
  log("websocket open");
  console.log(e);
};

ws.onclose = function(e){
  log("websocket close");
  console.log(e);
};

$(function(){
  $("#btn_post").click(post);
  $("#message").keydown(function(e){
    if(e.keyCode == 13) post();
  });
});

var post = function(){
  var name = $("#name").val();
  var mes = $("#message").val();
  ws.send(name+" : "+mes);
  $("input#message").val("");
};

var log = function(msg){
  console.log(msg);
  $("#chat").prepend($("<li>").text("[log] "+msg));
};

var print = function(msg){
  $("#chat").prepend($("<li>").text(msg));
};
</script>
 -->

app/views/prototype/next_round.js.erb
$('.baozi-list').html('<%= escape_javascript render "next_round" %>');